TIMEZONES = {
    "A": "UTC+1",  # Alfa Time Zone  (Military)
    "ACDT": "UTC+10:30",  # Australian Central Daylight Time  CDT – Central Daylight Time CDST – Central Daylight Savings Time  (Australia)
    "ACST": "UTC+9:30",  # Australian Central Standard Time  CST – Central Standard Time  (Australia)
    "ACT": "UTC-5",  # Acre Time  (South America)
    "ACWST": "UTC+8:45",  # Australian Central Western Standard Time  (Australia)
    "ADT": "UTC+4",  # Arabia Daylight Time  AST – Arabia Summer Time  (Asia)
    "ADT": "UTC-3",  # Atlantic Daylight Time  ADST – Atlantic Daylight Saving Time AST – Atlantic Summer Time  HAA – Heure Avancée de l"Atlantique (French) (North America Atlantic)
    "AEDT": "UTC+11",  # Australian Eastern Daylight Time  EDT – Eastern Daylight Time EDST – Eastern Daylight Saving Time  (Australia)
    "AEST": "UTC+10",  # Australian Eastern Standard Time  EST – Eastern Standard Time AET – Australian Eastern Time  (Australia)
    "AFT": "UTC+4:30",  # Afghanistan Time  (Asia)
    "AKDT": "UTC-8",  # Alaska Daylight Time  ADST – Alaska Daylight Saving Time  (North America)
    "AKST": "UTC-9",  # Alaska Standard Time  AT – Alaska Time  (North America)
    "ALMT": "UTC+6",  # Alma-Ata Time  (Asia)
    "AMST": "UTC-3",  # Amazon Summer Time  (South America)
    "AMST": "UTC+5",  # Armenia Summer Time  AMDT – Armenia Daylight Time  (Asia)
    "AMT": "UTC-4",  # Amazon Time  (South America)
    "AMT": "UTC+4",  # Armenia Time  (Asia)
    "ANAST": "UTC+12",  # Anadyr Summer Time  (Asia)
    "ANAT": "UTC+12",  # Anadyr Time  (Asia)
    "AQTT": "UTC+5",  # Aqtobe Time  (Asia)
    "ART": "UTC-3",  # Argentina Time  (Antarctica South America)
    "AST": "UTC+3",  # Arabia Standard Time  AST – Arabic Standard Time AST – Al Manamah Standard Time  (Asia)
    "AST": "UTC-4",  # Atlantic Standard Time  AT – Atlantic Time  AST – Tiempo Estándar del Atlántico (Spanish) HNA – Heure Normale de l"Atlantique (French) (North America Atlantic Caribbean)
    "AWDT": "UTC+9",  # Australian Western Daylight Time  WDT – Western Daylight Time WST – Western Summer Time  (Australia)
    "AWST": "UTC+8",  # Australian Western Standard Time  WST – Western Standard Time WAT – Western Australia Time  (Australia)
    "AZOST": "UTC+0",  # Azores Summer Time  AZODT – Azores Daylight Time  (Atlantic)
    "AZOT": "UTC-1",  # Azores Time  AZOST – Azores Standard Time  (Atlantic)
    "AZST": "UTC+5",  # Azerbaijan Summer Time  (Asia)
    "AZT": "UTC+4",  # Azerbaijan Time  (Asia)
    "AoE": "UTC-12",  # Anywhere on Earth  (Pacific)
    "B": "UTC+2",  # Bravo Time Zone  (Military)
    "BNT": "UTC+8",  # Brunei Darussalam Time  BDT – Brunei Time  (Asia)
    "BOT": "UTC-4",  # Bolivia Time  (South America)
    "BRST": "UTC-2",  # Brasília Summer Time  BST – Brazil Summer Time BST – Brazilian Summer Time  (South America)
    "BRT": "UTC-3",  # Brasília Time  BT – Brazil Time BT – Brazilian Time  (South America)
    "BST": "UTC+6",  # Bangladesh Standard Time  (Asia)
    "BST": "UTC+11",  # Bougainville Standard Time  (Pacific)
    "BST": "UTC+1",  # British Summer Time  BDT – British Daylight Time BDST – British Daylight Saving Time  (Europe)
    "BTT": "UTC+6",  # Bhutan Time  (Asia)
    "C": "UTC+3",  # Charlie Time Zone  (Military)
    "CAST": "UTC+8",  # Casey Time  (Antarctica)
    "CAT": "UTC+2",  # Central Africa Time  (Africa)
    "CCT": "UTC+6:30",  # Cocos Islands Time  (Indian Ocean)
    "CDT": "UTC-5",  # Central Daylight Time  CDST – Central Daylight Saving Time NACDT – North American Central Daylight Time  HAC – Heure Avancée du Centre (French) (North America)
    "CDT": "UTC-4",  # Cuba Daylight Time  (Caribbean)
    "CEST": "UTC+2",  # Central European Summer Time  CEDT – Central European Daylight Time ECST – European Central Summer Time  MESZ – Mitteleuropäische Sommerzeit (German) (Europe Antarctica)
    "CET": "UTC+1",  # Central European Time  ECT – European Central Time CET – Central Europe Time  MEZ – Mitteleuropäische Zeit (German) (Europe Africa)
    "CHADT": "UTC+13:45",  # Chatham Island Daylight Time  CDT – Chatham Daylight Time  (Pacific)
    "CHAST": "UTC+12:45",  # Chatham Island Standard Time  (Pacific)
    "CHOST": "UTC+9",  # Choibalsan Summer Time  CHODT – Choibalsan Daylight Time CHODST – Choibalsan Daylight Saving Time  (Asia)
    "CHOT": "UTC+8",  # Choibalsan Time  (Asia)
    "CHUT": "UTC+10",  # Chuuk Time  (Pacific)
    "CIDST": "UTC-4",  # Cayman Islands Daylight Saving Time  (Caribbean)
    "CIST": "UTC-5",  # Cayman Islands Standard Time  CIT – Cayman Islands Time  (Caribbean)
    "CKT": "UTC-10",  # Cook Island Time  (Pacific)
    "CLST": "UTC-3",  # Chile Summer Time  CLDT – Chile Daylight Time  (South America Antarctica)
    "CLT": "UTC-4",  # Chile Standard Time  CT – Chile Time CLST – Chile Standard Time  (South America Antarctica)
    "COT": "UTC-5",  # Colombia Time  (South America)
    "CST": "UTC-6",  # Central Standard Time  CT – Central Time NACST – North American Central Standard Time  CST – Tiempo Central Estándar (Spanish) HNC – Heure Normale du Centre (French) (North America Central America)
    "CST": "UTC+8",  # China Standard Time  (Asia)
    "CST": "UTC-5",  # Cuba Standard Time  (Caribbean)
    "CVT": "UTC-1",  # Cape Verde Time  (Africa)
    "CXT": "UTC+7",  # Christmas Island Time  (Australia)
    "ChST": "UTC+10",  # Chamorro Standard Time  GST – Guam Standard Time  (Pacific)
    "D": "UTC+4",  # Delta Time Zone  (Military)
    "DAVT": "UTC+7",  # Davis Time  (Antarctica)
    "DDUT": "UTC+10",  # Dumont-d"Urville Time  (Antarctica)
    "E": "UTC+5",  # Echo Time Zone  (Military)
    "EASST": "UTC-5",  # Easter Island Summer Time  EADT – Easter Island Daylight Time  (Pacific)
    "EAST": "UTC-6",  # Easter Island Standard Time  (Pacific)
    "EAT": "UTC+3",  # Eastern Africa Time  EAT – East Africa Time  (Africa Indian Ocean)
    "ECT": "UTC-5",  # Ecuador Time  (South America)
    "EDT": "UTC-4",  # Eastern Daylight Time  EDST – Eastern Daylight Savings Time NAEDT – North American Eastern Daylight Time  HAE – Heure Avancée de l"Est (French) EDT – Tiempo de verano del Este (Spanish) (North America Caribbean)
    "EEST": "UTC+3",  # Eastern European Summer Time  EEDT – Eastern European Daylight Time  OESZ – Osteuropäische Sommerzeit (German) (Europe Asia Africa)
    "EET": "UTC+2",  # Eastern European Time  OEZ – Osteuropäische Zeit (German) (Europe Asia Africa)
    "EGST": "UTC+0",  # Eastern Greenland Summer Time  EGST – East Greenland Summer Time  (North America)
    "EGT": "UTC-1",  # East Greenland Time  EGT – Eastern Greenland Time  (North America)
    "EST": "UTC-5",  # Eastern Standard Time  ET – Eastern Time  NAEST – North American Eastern Standard Time  ET – Tiempo del Este (Spanish) HNE – Heure Normale de l"Est (French) (North America Caribbean Central America)
    "F": "UTC+6",  # Foxtrot Time Zone  (Military)
    "FET": "UTC+3",  # Further-Eastern European Time  (Europe)
    "FJST": "UTC+13",  # Fiji Summer Time  FJDT – Fiji Daylight Time  (Pacific)
    "FJT": "UTC+12",  # Fiji Time  (Pacific)
    "FKST": "UTC-3",  # Falkland Islands Summer Time  FKDT – Falkland Island Daylight Time  (South America)
    "FKT": "UTC-4",  # Falkland Island Time  FKST – Falkland Island Standard Time  (South America)
    "FNT": "UTC-2",  # Fernando de Noronha Time  (South America)
    "G": "UTC+7",  # Golf Time Zone  (Military)
    "GALT": "UTC-6",  # Galapagos Time  (Pacific)
    "GAMT": "UTC-9",  # Gambier Time  GAMT – Gambier Islands Time  (Pacific)
    "GET": "UTC+4",  # Georgia Standard Time  (Asia Europe)
    "GFT": "UTC-3",  # French Guiana Time  (South America)
    "GILT": "UTC+12",  # Gilbert Island Time  (Pacific)
    "GMT": "UTC+0",  # Greenwich Mean Time  UTC– Coordinated Universal Time GT – Greenwich Time  (Europe Africa North America Antarctica)
    "GST": "UTC+4",  # Gulf Standard Time  (Asia)
    "GST": "UTC-2",  # South Georgia Time  (South America)
    "GYT": "UTC-4",  # Guyana Time  (South America)
    "H": "UTC+8",  # Hotel Time Zone  (Military)
    "HDT": "UTC-9",  # Hawaii-Aleutian Daylight Time  HADT – Hawaii Daylight Time  (North America)
    "HKT": "UTC+8",  # Hong Kong Time  (Asia)
    "HOVST": "UTC+8",  # Hovd Summer Time  HOVDT – Hovd Daylight Time HOVDST – Hovd Daylight Saving Time  (Asia)
    "HOVT": "UTC+7",  # Hovd Time  (Asia)
    "HST": "UTC-10",  # Hawaii Standard Time  HAST – Hawaii-Aleutian Standard Time  (North America Pacific)
    "I": "UTC+9",  # India Time Zone  (Military)
    "ICT": "UTC+7",  # Indochina Time  (Asia)
    "IDT": "UTC+3",  # Israel Daylight Time  (Asia)
    "IOT": "UTC+6",  # Indian Chagos Time  (Indian Ocean)
    "IRDT": "UTC+4:30",  # Iran Daylight Time  IRST – Iran Summer Time IDT – Iran Daylight Time  (Asia)
    "IRKST": "UTC+9",  # Irkutsk Summer Time  (Asia)
    "IRKT": "UTC+8",  # Irkutsk Time  (Asia)
    "IRST": "UTC+3:30",  # Iran Standard Time  IT – Iran Time  (Asia)
    "IST": "UTC+5:30",  # India Standard Time  IT – India Time IST – Indian Standard Time  (Asia)
    "IST": "UTC+1",  # Irish Standard Time  IST – Irish Summer Time  (Europe)
    "IST": "UTC+2",  # Israel Standard Time  (Asia)
    "JST": "UTC+9",  # Japan Standard Time  (Asia)
    "K": "UTC+10",  # Kilo Time Zone  (Military)
    "KGT": "UTC+6",  # Kyrgyzstan Time  (Asia)
    "KOST": "UTC+11",  # Kosrae Time  (Pacific)
    "KRAST": "UTC+8",  # Krasnoyarsk Summer Time  (Asia)
    "KRAT": "UTC+7",  # Krasnoyarsk Time  (Asia)
    "KST": "UTC+9",  # Korea Standard Time  KST – Korean Standard Time KT – Korea Time  (Asia)
    "KUYT": "UTC+4",  # Kuybyshev Time  SAMST – Samara Summer Time  (Europe)
    "L": "UTC+11",  # Lima Time Zone  (Military)
    "LHDT": "UTC+11",  # Lord Howe Daylight Time  (Australia)
    "LHST": "UTC+10:30",  # Lord Howe Standard Time  (Australia)
    "LINT": "UTC+14",  # Line Islands Time  (Pacific)
    "M": "UTC+12",  # Mike Time Zone  (Military)
    "MAGST": "UTC+12",  # Magadan Summer Time  MAGST – Magadan Island Summer Time  (Asia)
    "MAGT": "UTC+11",  # Magadan Time  MAGT – Magadan Island Time  (Asia)
    "MART": "UTC-9:30",  # Marquesas Time  (Pacific)
    "MAWT": "UTC+5",  # Mawson Time  (Antarctica)
    "MDT": "UTC-6",  # Mountain Daylight Time  MDST – Mountain Daylight Saving Time NAMDT – North American Mountain Daylight Time  HAR – Heure Avancée des Rocheuses (French) (North America)
    "MHT": "UTC+12",  # Marshall Islands Time  (Pacific)
    "MMT": "UTC+6:30",  # Myanmar Time  (Asia)
    "MSD": "UTC+4",  # Moscow Daylight Time  Moscow Summer Time  (Europe)
    "MSK": "UTC+3",  # Moscow Standard Time  MCK – Moscow Time  (Europe Asia)
    "MST": "UTC-7",  # Mountain Standard Time  MT – Mountain Time NAMST – North American Mountain Standard Time  HNR – Heure Normale des Rocheuses (French) (North America)
    "MUT": "UTC+4",  # Mauritius Time  (Africa)
    "MVT": "UTC+5",  # Maldives Time  (Asia)
    "MYT": "UTC+8",  # Malaysia Time  MST – Malaysian Standard Time  (Asia)
    "N": "UTC-1",  # November Time Zone  (Military)
    "NCT": "UTC+11",  # New Caledonia Time  (Pacific)
    "NDT": "UTC-2:30",  # Newfoundland Daylight Time  HAT – Heure Avancée de Terre-Neuve (French) (North America)
    "NFDT": "UTC+12",  # Norfolk Daylight Time  NFDT – Norfolk Island Daylight Time  (Australia)
    "NFT": "UTC+11",  # Norfolk Time  NFT – Norfolk Island Time  (Australia)
    "NOVST": "UTC+7",  # Novosibirsk Summer Time  OMSST – Omsk Summer Time  (Asia)
    "NOVT": "UTC+7",  # Novosibirsk Time  OMST – Omsk Standard Time  (Asia)
    "NPT": "UTC+5:45",  # Nepal Time  (Asia)
    "NRT": "UTC+12",  # Nauru Time  (Pacific)
    "NST": "UTC-3:30",  # Newfoundland Standard Time  HNT – Heure Normale de Terre-Neuve (French) (North America)
    "NUT": "UTC-11",  # Niue Time  (Pacific)
    "NZDT": "UTC+13",  # New Zealand Daylight Time  (Pacific Antarctica)
    "NZST": "UTC+12",  # New Zealand Standard Time  (Pacific Antarctica)
    "O": "UTC-2",  # Oscar Time Zone  (Military)
    "OMSST": "UTC+7",  # Omsk Summer Time  NOVST – Novosibirsk Summer Time  (Asia)
    "OMST": "UTC+6",  # Omsk Standard Time  OMST – Omsk Time NOVT – Novosibirsk Time  (Asia)
    "ORAT": "UTC+5",  # Oral Time  (Asia)
    "P": "UTC-3",  # Papa Time Zone  (Military)
    "PDT": "UTC-7",  # Pacific Daylight Time  PDST – Pacific Daylight Saving Time NAPDT – North American Pacific Daylight Time  HAP – Heure Avancée du Pacifique (French) (North America)
    "PET": "UTC-5",  # Peru Time  (South America)
    "PETST": "UTC+12",  # Kamchatka Summer Time  (Asia)
    "PETT": "UTC+12",  # Kamchatka Time  PETT – Petropavlovsk-Kamchatski Time  (Asia)
    "PGT": "UTC+10",  # Papua New Guinea Time  (Pacific)
    "PHOT": "UTC+13",  # Phoenix Island Time  (Pacific)
    "PHT": "UTC+8",  # Philippine Time  PST – Philippine Standard Time  (Asia)
    "PKT": "UTC+5",  # Pakistan Standard Time  PKT – Pakistan Time  (Asia)
    "PMDT": "UTC-2",  # Pierre & Miquelon Daylight Time  (North America)
    "PMST": "UTC-3",  # Pierre & Miquelon Standard Time  (North America)
    "PONT": "UTC+11",  # Pohnpei Standard Time  (Pacific)
    "PST": "UTC-8",  # Pacific Standard Time  PT – Pacific Time NAPST – North American Pacific Standard Time  PT – Tiempo del Pacífico (Spanish) HNP – Heure Normale du Pacifique (French) (North America)
    "PST": "UTC-8",  # Pitcairn Standard Time  (Pacific)
    "PWT": "UTC+9",  # Palau Time  (Pacific)
    "PYST": "UTC-3",  # Paraguay Summer Time  (South America)
    "PYT": "UTC-4",  # Paraguay Time  (South America)
    "PYT": "UTC+8:30",  # Pyongyang Time  PYST – Pyongyang Standard Time  (Asia)
    "Q": "UTC-4",  # Quebec Time Zone  (Military)
    "QYZT": "UTC+6",  # Qyzylorda Time  (Asia)
    "R": "UTC-5",  # Romeo Time Zone  (Military)
    "RET": "UTC+4",  # Reunion Time  (Africa)
    "ROTT": "UTC-3",  # Rothera Time  (Antarctica)
    "S": "UTC-6",  # Sierra Time Zone  (Military)
    "SAKT": "UTC+11",  # Sakhalin Time  (Asia)
    "SAMT": "UTC+4",  # Samara Time  SAMT – Samara Standard Time  (Europe)
    "SAST": "UTC+2",  # South Africa Standard Time  SAST – South African Standard Time  (Africa)
    "SBT": "UTC+11",  # Solomon Islands Time  SBT – Solomon Island Time  (Pacific)
    "SCT": "UTC+4",  # Seychelles Time  (Africa)
    "SGT": "UTC+8",  # Singapore Time  SST – Singapore Standard Time  (Asia)
    "SRET": "UTC+11",  # Srednekolymsk Time  (Asia)
    "SRT": "UTC-3",  # Suriname Time  (South America)
    "SST": "UTC-11",  # Samoa Standard Time  (Pacific)
    "SYOT": "UTC+3",  # Syowa Time  (Antarctica)
    "T": "UTC-7",  # Tango Time Zone  (Military)
    "TAHT": "UTC-10",  # Tahiti Time  (Pacific)
    "TFT": "UTC+5",  # French Southern and Antarctic Time  KIT – Kerguelen (Islands) Time  (Indian Ocean)
    "TJT": "UTC+5",  # Tajikistan Time  (Asia)
    "TKT": "UTC+13",  # Tokelau Time  (Pacific)
    "TLT": "UTC+9",  # East Timor Time  (Asia)
    "TMT": "UTC+5",  # Turkmenistan Time  (Asia)
    "TOST": "UTC+14",  # Tonga Summer Time  (Pacific)
    "TOT": "UTC+13",  # Tonga Time  (Pacific)
    "TRT": "UTC+3",  # Turkey Time  (Asia Europe)
    "TVT": "UTC+12",  # Tuvalu Time  (Pacific)
    "U": "UTC-8",  # Uniform Time Zone  (Military)
    "ULAST": "UTC+9",  # Ulaanbaatar Summer Time  ULAST – Ulan Bator Summer Time  (Asia)
    "ULAT": "UTC+8",  # Ulaanbaatar Time  ULAT – Ulan Bator Time  (Asia)
    "UTC": "UTC",  # Coordinated Universal Time  (Worldwide)
    "UYST": "UTC-2",  # Uruguay Summer Time  (South America)
    "UYT": "UTC-3",  # Uruguay Time  (South America)
    "UZT": "UTC+5",  # Uzbekistan Time  (Asia)
    "V": "UTC-9",  # Victor Time Zone  (Military)
    "VET": "UTC-4",  # Venezuelan Standard Time  HLV – Hora Legal de Venezuela (Spanish) (South America)
    "VLAST": "UTC+11",  # Vladivostok Summer Time  (Asia)
    "VLAT": "UTC+10",  # Vladivostok Time  (Asia)
    "VOST": "UTC+6",  # Vostok Time  (Antarctica)
    "VUT": "UTC+11",  # Vanuatu Time  EFATE – Efate Time  (Pacific)
    "W": "UTC-10",  # Whiskey Time Zone  (Military)
    "WAKT": "UTC+12",  # Wake Time  (Pacific)
    "WARST": "UTC-3",  # Western Argentine Summer Time  (South America)
    "WAST": "UTC+2",  # West Africa Summer Time  (Africa)
    "WAT": "UTC+1",  # West Africa Time  (Africa)
    "WEST": "UTC+1",  # Western European Summer Time  WEDT – Western European Daylight Time  WESZ – Westeuropäische Sommerzeit (German) (Europe Africa)
    "WET": "UTC+0",  # Western European Time  GMT – Greenwich Mean Time  WEZ – Westeuropäische Zeit (German) (Europe Africa)
    "WFT": "UTC+12",  # Wallis and Futuna Time  (Pacific)
    "WGST": "UTC-2",  # Western Greenland Summer Time  WGST – West Greenland Summer Time  (North America)
    "WGT": "UTC-3",  # West Greenland Time  WGT – Western Greenland Time  (North America)
    "WIB": "UTC+7",  # Western Indonesian Time  WIB – Waktu Indonesia Barat  (Asia)
    "WIT": "UTC+9",  # Eastern Indonesian Time  WIT – Waktu Indonesia Timur  (Asia)
    "WITA": "UTC+8",  # Central Indonesian Time  WITA – Waktu Indonesia Tengah  (Asia)
    "WST": "UTC+13",  # West Samoa Time  ST – Samoa Time  (Pacific)
    "WST": "UTC+1",  # Western Sahara Summer Time  (Africa)
    "WT": "UTC+0",  # Western Sahara Standard Time  WT – Western Sahara Time  (Africa)
    "X": "UTC-11",  # X-ray Time Zone  (Military)
    "Y": "UTC-12",  # Yankee Time Zone  (Military)
    "YAKST": "UTC+10",  # Yakutsk Summer Time  (Asia)
    "YAKT": "UTC+9",  # Yakutsk Time  (Asia)
    "YAPT": "UTC+10",  # Yap Time  (Pacific)
    "YEKST": "UTC+6",  # Yekaterinburg Summer Time  (Asia)
    "YEKT": "UTC+5",  # Yekaterinburg Time  (Asia)
    "Z": "UTC+0",  # Zulu Time Zone  (Military)
}